services:
  frontend:
    image: matcha-frontend
    container_name: matcha-frontend
    build:
      context: ./apps/
      dockerfile: ./docker/frontend/Dockerfile
    env_file:
      - .env-frontend
    volumes:
      - ./apps/frontend/:/app/frontend
      - node_modules-data:/app/frontend/node_modules
    networks:
      - matcha-network

  backend:
    image: matcha-backend
    container_name: matcha-backend
    build:
      context: ./apps/
      dockerfile: ./docker/backend/Dockerfile
    env_file:
      - .env-backend
    volumes:
      - ./apps/backend/:/app/backend
      - node_modules-data2:/app/backend/node_modules
    depends_on:
      - db
    networks:
      - matcha-network

  db:
    container_name: matcha-db
    image: postgres:16
    env_file:
      - .env-db
    networks:
      - matcha-network
    volumes:
      - matcha-db-data:/var/lib/postgresql/data

  nginx:
    image: matcha-nginx
    container_name: matcha-nginx
    build:
      context: .
      dockerfile: apps/docker/nginx/Dockerfile
    networks:
      - matcha-network
    ports:
      - 80:80

  adminer:
    image: adminer
    container_name: matcha-adminer
    networks:
      - matcha-network
    ports:
      - 8080:8080

volumes:
  matcha-db-data:
  node_modules-data:
    name: node_modules-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./apps/frontend/node_modules
  node_modules-data2:
    name: node_modules-data2
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./apps/backend/node_modules

networks:
  matcha-network:
    driver: bridge
